### ISSUE TITLE
Join sometimes not applied to query, when query is called multiple times

### ISSUE THREAD

**Issue by jtomlinson** [kirschbaum-development/eloquent-power-joins#148]
### Context
PHP: 8.1
Laravel: 10.18.0
PowerJoins: 3.2.1

I am running into an issue where sometimes a power join is not applied to a query when the query is fired multiple times quickly. I was able to narrow it down to the following code in JoinRelationship.php on line 131. If I comment out this code, the example below never fails.

```
if ($joinHelper->relationshipAlreadyJoined($this->getModel(), $relationJoinCache)) {
    return $this;
}
```

I am able to consistently reproduce this issue in Tinkerwell with the following code.

```
for ($x = 0; $x < 100; $x++) {
  try {
    PhysicalInventoryData::select(['users.first_last_initial', 'users.full_name'])
      ->where('physical_inventory_id', 1929)
      ->where('last_scanned_by', '!=', 0)
      ->joinRelationship('User')
      ->orderBy('users.full_name')
      ->pluck('users.full_name', 'users.first_last_initial'); 
  } catch (Exception $e) {
    ray($x);
  }
}
```

The code fails every third iteration, every time I run this, with the following error.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.first_last_initial' in 'field list' (Connection: physical, SQL: select `users`.`first_last_initial`, `users`.`full_name` from `physical`.`physical_inventory_data` where `physical_inventory_id` = 1929 and `last_scanned_by` != 0 and `physical`.`physical_inventory_data`.`deleted_at` is null order by `users`.`full_name` asc)

The reason this came to light for me, is during tests sometimes the same query is run multiple times with different parameters and randomly fails with this same error. I looked at the power join code to see if I could figure out what was happening, but wasn't able to. If you need any more information, please let me know.

**Comment by jwohlfert23** [comment]
+1

**Comment by luisdalmolin** [comment]
I'll take a look at this

**Comment by tobyzerner** [comment]
I'm also running into a sporadic join-related error in my app running on Octane, and I believe this issue would explain it.

**Comment by luisdalmolin** [comment]
@jtomlinson @tobyzerner @jwohlfert23 what version are you guys using?

**Comment by jtomlinson** [comment]
> @jtomlinson @tobyzerner @jwohlfert23 what version are you guys using?

3.2.1

**Comment by denxdv** [comment]
The same. Quite a sneaky bug. You get it If you run Product::all() in forach with joinRealtion. And the most interesting thing is that this happens with different instances of products when you start foreach again. Also, it works in different ways on different servers. So, tests on a dev server can be passed but then it can break down the site on production if there are more products in foreach f.e. 
According to my investigation, it happens because spl_object_id can reuse id if garbage collector destroyed an object, so you get the same instance for the JoinsHelper. My idea is to set property to object dynamically with uniqid() like $product->powerJoinWasLoaded = uniqid(); and use it instead of spl_object_id($object).
It's shown on the screenshot how I identified this problem
<img width="690" alt="image" src="https://github.com/kirschbaum-development/eloquent-power-joins/assets/52453110/06e16a78-f10f-4619-a2f3-4ada2de979b3">
 This is a really important update for me and not only I believe

**Comment by luisdalmolin** [comment]
Can you guys test with the new version I just pushed? This should be fixed.

**3.2.4**

**Comment by jtomlinson** [comment]
> Can you guys test with the new version I just pushed? This should be fixed.
> 
> **3.2.4**

Seems to be working for me. Thank you.

**Comment by denxdv** [comment]
Still getting the same error unfortunately :(
My code in tinker
\App\Models\Product::all()->each(function($p){echo $p->id. " => ". $p->available; echo PHP_EOL;});
"available" is relation and there is used "->joinRelation('productOption')"
Getting error like that
<img width="1239" alt="image" src="https://github.com/kirschbaum-development/eloquent-power-joins/assets/52453110/3d53bc7b-7c99-41ce-a750-2bd4e6040569">

**Comment by sebj54** [comment]
I also had this problem today. 

The issue was caused by a loop which did this:

```php
$builder = MyModel::select('my_column');
```

Instead, I am using the code below, which creates a new model instance under the hood, which does not cause the issue (because we now have a new unique object ID): 

```php
$builder = MyModel::query();
$builder->select('my_column');
```

**Comment by luisdalmolin** [comment]
Yes, this is a bit tricky as if you don't do it reuses the same object in memory. I personally think it would be a good pattern for Laravel to always call `query()` before making a query so it's explicit.
